qaqc_data_location: /Users/ryanmcclure/Documents/SUGG-forecast/qaqc_data
data_location: /Users/ryanmcclure/Documents/SUGG-forecast/data

##########################
# Lake information
###########################

lake_name_code: SUGG
lake_name: Suggs Lake
lake_latitude: 29.68778   #Degrees North
lake_longitude: -82.017745  #Degrees West

#Time zone that GLM is run in
#Currently needed to be GMT so that it interfaces with the NOAA forecast
#reference_tzone <<- "GMT"
#Local time zone of the lake
local_tzone: "EST"

##########################
#  Information required to generate EML metadata file
##########################

metadata:
    forecast_project_id: test_neon
    generate_eml: TRUE
    abstract: "Forecasts for Suggs Lake in Florida"
    forecast_title: FLARE
    intellectualRights: insert license
    model_description:
        forecast_model_id: https://github.com/rqthomas/flare/commit/d1ddcb07b9d28863890597503fc4aa4a4496de56
        name: General Lake Model
        type: process-based
        repository: https://github.com/AquaticEcoDynamics/GLM/releases/tag/v3.1.0
    me:
        individualName:
              givenName: "Ryan"
              surName: "McClure"
        electronicMailAddress:  "ryan333@vt.edu"
        id: 0000-0001-6370-3852



############################
# Run information
#############################

model_name: glm_aed #other is "null"

base_GLM_nml: configuration_files/glm3.nml

#All sources of uncertainty and data used to constrain
use_obs_constraint: TRUE
observation_uncertainty: TRUE
process_uncertainty: TRUE
weather_uncertainty: TRUE
initial_condition_uncertainty: TRUE
parameter_uncertainty: TRUE
met_downscale_uncertainty: TRUE
inflow_process_uncertainty: TRUE

#########################
### Depth information
#########################
#Depths used in the EnKF
#This are the depths that are saved between days
#Init depth of lake
#########################
### Depth information
#########################
#Depths used in the EnKF
#This are the depths that are saved between days
#Init depth of lake
lake_depth_init: 3.1  #not a modeled state

modeled_depths: [0.00,0.10,0.50,1.00,
                 1.50,2.00,2.50,3.00]

depths_bins_top: [0.00,0.10,0.50,1.00,
                 1.50,2.00,2.50,3.00]

default_temp_init: [16,16,16,16,
                    16,16,16,16]
                    
default_temp_init_depths: [0.00,0.10,0.50,1.00,
                           1.50,2.00,2.50,3.00]

the_sals_init: 0.0
default_snow_thickness_init: 0.0
default_white_ice_thickness_init: 0.0
default_blue_ice_thickness_init: 0.0

#########
#  Management
########

simulate_sss: FALSE
sss_depth: .na
use_specified_sss: FALSE
specified_sss_inflow_file: .na
specified_sss_outflow_file: .na
forecast_sss_flow: .na
forecast_sss_oxy: .na
#umol/m3  of oxygen if SSS turned on in forecast
sss_fname: FALSE
sss_inflow_factor: .na



##############################
##  EnKF setup
##############################
ensemble_size:  100 #221 #441
localization_distance: .na #distance in meters were covariances in the model error are used
vert_decorr_length: 5.0
no_negative_states: TRUE
assimilate_first_step: FALSE
ncore: 5

#################################
# Parameter calibration information
#################################

par_file: parameter_calibration_config.csv

#####################################
###  Observation information
######################################

obs_config_file: observations_config.csv

#########################################
###  State information
#########################################

states_config_file: states_config.csv
states_config_process_error: states_process_error.csv

########################################
# Dignostics
#######################################

diagnostics_names:  [extc_coef]


